### ISSUE TITLE
Delete template from index view fails

### ISSUE THREAD

**Issue by tiloschroeder** [michael-e/email_template_manager#100]
When I want to delete a template from the index view, I get the following error message:
```
Access Denied
Request was rejected for having an invalid cross-site request forgery token.
```
This happens because no XSRF token is passed.

Call me old-school, but I wouldn't allow deleting from the index view at all. A template is quickly deleted by mistake: wrong line selected, misleading template name, etc.

On the edit page of the template you can see exactly what it is for (data sources, recipients, etc.). Therefore I would only allow it from this page.

For this you just need to comment out in file ```content/templates/viewIndex.xsl```  line 32-42 (```<div class="actions">...</div>```).

This issue has nothing to do with PHP 8 ;-)

**Comment by michael-e** [comment]
This is a bug, and I will fix it. I will also care for #78, which has been here for quite a while.

Deleting blueprints (like pages, sections, events, datasources...) from the index view is generally possible in Symphony, so for consistency's sake the feature should not be removed.

**Comment by tiloschroeder** [comment]
> Deleting blueprints (like pages, sections, events, datasources...) from the index view is generally possible in Symphony, so for consistency's sake the feature should not be removed.

OK. :-)

I've already figured out #78 and will post it after the long weekend.

Nice weekend.

**Comment by michael-e** [comment]
I already fixed it, with my commit some minutes ago! :-)
