### ISSUE TITLE
Undefined array key "parent"

### ISSUE THREAD

**Issue by tiloschroeder** [michael-e/email_template_manager#101]
Every time I edit a data source and then save it, I get the following error message:

```
Symphony Warning: Undefined array key "parent"
An error occurred in /srv/www/htdocs/symphony-php8/extensions/email_template_manager/extension.driver.php around line 84
```
This is what ```$file``` returns:

```
array(4) {
  ["file"]=>
  string(69) "/srv/www/htdocs/symphony-php8/workspace/data-sources/data.test.php"
  ["previous_file"]=>
  NULL
  ["page"]=>
  array(2) {
    [0]=>
    string(24) "/blueprints/datasources/"
    [1]=>
    string(1) "*"
  }
  ["delegate"]=>
  string(18) "DatasourcePostEdit"
}
```

The following solution works for me: 

```php
if (array_key_exists('parent', $file)) {
    ...
}
```

**Comment by tiloschroeder** [comment]
> Does this array key ever exist? Or has this always been broken?

🤷‍♂️

For my understanding the whole function is obsolet. What has an editing of a data source to do with the selected data sources in an email template? This error occurs even if the data source is selected not in a single email templete.
Or is it for the "Verklöppelung" in the database?

**Comment by michael-e** [comment]
I think that the function is supposed to care for renaming of data sources, automatically "pushing" the new name/handle in the template's datasource array. So the function is not useless, it just seems broken to me.

**Comment by tiloschroeder** [comment]
Just tested with 2.7.10 under PHP 7.4: same return from ```$file``` as above.

**Comment by michael-e** [comment]
I will try and look into it.

**Comment by tiloschroeder** [comment]
> I will try and look into it.

👍 thx.

**Comment by michael-e** [comment]
Related: #102

**Comment by michael-e** [comment]
Please test the fix in the development branch.

**Comment by tiloschroeder** [comment]
this is the response of ```$file``` if the data source is attached to an email template and if it is renamed:

```
array(4) {
  ["file"]=>
  string(70) "/srv/www/htdocs/sym_php7/workspace/data-sources/data.teste.php"
  ["previous_file"]=>
  string(69) "/srv/www/htdocs/sym_php7/workspace/data-sources/data.test.php"
  ["page"]=>
  array(2) {
    [0]=>
    string(24) "/blueprints/datasources/"
    [1]=>
    string(1) "*"
  }
  ["delegate"]=>
  string(18) "DatasourcePostEdit"
}
```

**Comment by tiloschroeder** [comment]
> Please test the fix in the development branch.

yep, will do after dinner. ;-)

**Comment by tiloschroeder** [comment]
> Please test the fix in the development branch.

👌 good job. works on 2.7.10/7.4 and 2.7.10+PHP8-fixes/8.
