### ISSUE TITLE
Call to undefined method Administration::Page()

### ISSUE THREAD

**Issue by animaux** [michael-e/email_template_manager#103]
@michael-e, bis Du noch hier zugegen? Nachdem Gitter der Enshittification zum Opfer gefallen ist, hab ich ansonsten keinen Kanal mehr zu Dir …

Ich bekomme bei einer Site gerade in einem neu angelegten Event mit neu erstelltem Mail-Filter ein:

`Call to undefined method Administration::Page()`

`An error occurred in /var/www/html/extensions/email_template_manager/extension.driver.php around line 123`

—> `Symphony::Engine()->Page()->_param['etm-entry-id'] = $context['entry']->get('id');`

Ich habe in der gleichen Installation aber auch eine funktionerende E-Mail-Benachrichtigung, woran könnte das Problem liegen. Evtl. ein Rechte-Problem?

Viele Grüße,

Alex

**Comment by michael-e** [comment]
Yes, I am still here. :-)

I have no idea why this happens, and I wonder why the behavior is so "singular". Please try and test a bit more, there must be a difference!

**Comment by animaux** [comment]
`\o/` I’m poking around already.

**Comment by animaux** [comment]
I have to fight with some admins security layer mess the whole time … will try if it runs on a local dev server.

**Comment by michael-e** [comment]
OK, I will check back later. (AFK for two hours.)

**Comment by animaux** [comment]
I can’t get my head around it. Everything looks the same in the working E-Mail-Template and it’s settings. However I get the same error with that form even if I choose another E-Mail-Template. So the problem could be somehow related to the form or the frontend editing event.

**Comment by michael-e** [comment]
Have you tried on the local server?

**Comment by animaux** [comment]
OK, I think I found the issue. I have a hacked version of the experimental entry_versions extensions in the section. There seems to be a clash somewhere. When I remove the versions-field it’s running. But then again I need to have that in the current setup. I wonder what could be the problem, some timing-clash?

**Comment by michael-e** [comment]
I don't know how Entry Versions works, so I guess I can't help here. You may have to debug the issue step by step, e.g. by throwing custom errors, manually.

**Comment by animaux** [comment]
😩 that’s perfect for a PHP pro like me. I was already proud that I managed to get it working with frontend forms … I actually commented out a line that sent a status message, but apparently in the wrong part of an array, which resulted in a error. However I’m totally clueless …

**Comment by michael-e** [comment]
Is it PHP8???

**Comment by animaux** [comment]
Yeeees ;)

**Comment by animaux** [comment]
But the error is the same in PHP 7.4, so that’s not the root of problem apparently.

**Comment by michael-e** [comment]
Hmmm...

**Comment by animaux** [comment]
No PHP Errors.

**Comment by michael-e** [comment]
Symphony suppresses errors, you might change that! Set `error_reporting_all` to `yes` in `config.php`.

**Comment by animaux** [comment]
In `'symphony' => array(` ? Doesn’t seem to change anything.

**Comment by michael-e** [comment]
Yes, but I admit that I never tried it; the effect might depend on the server's settings.

**Comment by michael-e** [comment]
Also nothing in the Symphony log? The Apache log?

**Comment by animaux** [comment]
Nope :(

**Comment by michael-e** [comment]
Can you post the complete Symphony error page/backtrace?

**Comment by animaux** [comment]
Good moning. Sure!

## Symphony Fatal Error: Call to undefined method Administration::Page()

An error occurred in /…/extensions/email_template_manager/extension.driver.php around line 127

```php 
122
123 $template->addParams(array('etm-entry-id' => $context['entry']->get('id')));
124
125                         var_dump($context['entry']->get('id'));
126
127 Symphony::Engine()->Page()->_param['etm-entry-id'] = $context['entry']->get('id');
128
129 //Add POST as page parameters
130 foreach ($context['fields'] as $field => $val) {
131 if (is_array($val)) {
```

### Backtrace

```
[/…/extensions/email_template_manager/extension.driver.php:112]
    extension_email_template_manager->_sendEmail();
[/…/symphony/lib/toolkit/class.extensionmanager.php:702]
    extension_email_template_manager->eventFinalSaveFilter();
[/…/symphony/lib/toolkit/events/class.event.section.php:599]
    ExtensionManager::notifyMembers();
[/…/symphony/lib/toolkit/events/class.event.section.php:414]
    SectionEvent->processFinalSaveFilters();
[/…/symphony/lib/toolkit/events/class.event.section.php:281]
    SectionEvent->__doit();
[/…/symphony/lib/toolkit/class.event.php:157]
    SectionEvent->execute();
[/…/workspace/events/event.beispiel_abgeben.php:75]
    Event->__trigger();
[/…/symphony/lib/toolkit/class.frontendpage.php:761]
    eventbeispiel_abgeben->load();
[/…/symphony/lib/toolkit/class.frontendpage.php:457]
    FrontendPage->processEvents();
[/…/symphony/lib/toolkit/class.frontendpage.php:193]
    FrontendPage->__buildPage();
[/…/symphony/lib/core/class.frontend.php:106]
    FrontendPage->generate();
[/…/symphony/lib/boot/func.utilities.php:253]
    Frontend->display();
[/…/symphony/lib/boot/func.utilities.php:235]
    symphony_launcher();
[/…/index.php:19]
    symphony();
```

### Database Query Log

``` mysql
[0.0002] SET character_set_connection = 'utf8', character_set_database = 'utf8', character_set_server = 'utf8';
[0.0001] SET CHARACTER SET 'utf8';
[0.0001] SET time_zone = '+01:00';
```

**Comment by animaux** [comment]
If I dump `Symphony::Engine()` right before the call I get:

```php 
object(Administration)[51] private '_currentPage' => null private '_callback' => null public 'Page' => null
```

**Comment by animaux** [comment]
From my very esoteric understanding of what happens when saving the entry I’d thing the `entry_versions` extensions uses some process (hook, delegate?) that `etm` also uses and possibly »overwrites« something, so `etm` can’t access it anymore?

But `etm` uses `'delegate' => 'EventFinalSaveFilter',`, whereas `entry_versions` uses `'delegate' => 'EventPostSaveFilter',`.

**Comment by michael-e** [comment]
This shouldn't be, because you are in the frontend, right? Let me explain.

`Symphony::Engine()` must always either return the `Administration` or the `Frontend` object, automatically. The latter would be correct in the frontend context, i.e. on a frontend page. You can try it directly — change your `var_dump` in line 125 to:

```php
var_dump(Frontend::Page()); die();
```

This should dump the whole page object. Does it?

If I dump `Symphony::Engine()` in line 125, I get:

```php
object(Frontend)#8 (1) {
  ["_env"]=>
  array(0) {
  }
}
```

That is a frontend object!

**Comment by michael-e** [comment]
So probably one of your extensions (or a change to the Symphony core?) kind of "fools" the `Engine()`. You find this function in line 135 of `lib/core/class.symphony.php`. It is pretty simple:

```php
    public static function Engine()
    {
        if (class_exists('Administration', false)) {
            return Administration::instance();
        } elseif (class_exists('Frontend', false)) {
            return Frontend::instance();
        } else {
            throw new Exception(__('No suitable engine object found'));
        }
    }
```

**Comment by animaux** [comment]
Thanks, sorry, I dumped the page first. I will try and find out what Nick has done back then :)

**Comment by michael-e** [comment]
So you have the frontend page object, but `Symphony::Engine()` returns an `Administration` object. Could it be that Entry Versions introduces the Administration class to the mix (which makes the Engine return the wrong object)?

**Comment by michael-e** [comment]
`EventPostSaveFilter` is triggered before the `EventFinalSaveFilter` in `class.event.section.php`:

```php
$result = $this->processPostSaveFilters($result, $fields, $entry);
$result = $this->processFinalSaveFilters($result, $fields, $entry);
```

**Comment by animaux** [comment]
> `EventPostSaveFilter` is triggered before the `EventFinalSaveFilter` in `class.event.section.php`:
> 
> ```
> $result = $this->processPostSaveFilters($result, $fields, $entry);
> $result = $this->processFinalSaveFilters($result, $fields, $entry);
> ```

OK, so this makes sense in terms of `entry_versions` fucking things up before `etm` comes in the game. I still have to find the spot where `entry_versions` messes with the `Engine()`.

**Comment by animaux** [comment]
This is actually beginning to be fun" `;)`.

**Comment by michael-e** [comment]
Strange people here. `:-(`

**Comment by animaux** [comment]
Looks like [this line](https://github.com/animaux/entry_versions/blob/9ed4d28915466f626fa48a9061d604b729978784/lib/class.entryversionsmanager.php#L60) is flipping the switch. If I dump the engine before `$data = ` it still shows frontend, and afterwards it becomes admin.

```php
'created-by' => ((Administration::instance()->Author()) ? Administration::instance()->Author()->getFullName() : 'frontend user'),
```

**Comment by animaux** [comment]
So I guess I could introduce a variable before this line that checks if we are in admin- or frontend-engine and only call the `Administration::instance()` if I am in the backend instead of directly checling for the `->Author`?

**Comment by michael-e** [comment]
Sounds like you found the issue!

**Comment by animaux** [comment]
Actually that is what Nick does in the field:

```php
$author = 'frontend user';
if(Symphony::Engine() instanceOf Administration) {
	$author = Administration::instance()->Author()->getFullName();
}
```

**Comment by animaux** [comment]
> Sounds like you found the issue!

Thanks so much for your help!

**Comment by michael-e** [comment]
Yes, that might solve the thing. Please try and come back!

**Comment by michael-e** [comment]
> Thanks so much for your help!

You're welcome!

**Comment by michael-e** [comment]
Shall we close this issue?

**Comment by animaux** [comment]
DIE SCHEISSE GEHT! `:D`

**Comment by animaux** [comment]
Yes please!

**Comment by michael-e** [comment]
> DIE SCHEISSE GEHT!

LOL

**Comment by animaux** [comment]
Fixed via https://github.com/animaux/entry_versions/commit/9ac79beca8d3c6db5db6d28e0a311563fa87c269
