### ISSUE TITLE
Allow HTTP URLs for attachments

### ISSUE THREAD

**Issue by michael-e** [michael-e/email_template_manager#89]
There has been a discussion with @jonmifsud on Gitter.

One might allow HTTP URLs for attachments by replacing this block:

``` php
foreach ($atts as $att) {
    $atts_eval[] = DOCROOT . $this->evalXPath($att, false);
}
```

in `class.emailtemplate.php` with:

``` php
foreach ($atts as $att) {
    $att = $this->evalXPath($att, false);
    if (filter_var($att, FILTER_VALIDATE_URL)) {
        $atts_eval[] = $att;
    } else {
        $atts_eval[] = DOCROOT . $att;
    }
}
```

However, this would have to be documented well:
1. Using HTTP is really inefficient if every recipient gets the same attachment, especially for mass emails (using the Email Newsletter Manager). In these cases it would be much better to download the file once and define it using the local path. This can be done by an event filter, for example.
2. Since multiple attachments are separated by commas in the configuration, we would have to disallow commas in URLs. This has been a no-brainer for the local path, but URLs like `http://example.com/images?color=red,green` might occur and are an issue.

**Comment by wdebusschere** [comment]
This would allow to send dynamically generated PDF's with the pdf extension.

**Comment by michael-e** [comment]
I am not sure which PDF extension you mean. Does it only generate PDFs via frontend URLs? No way to save to the local filesystem?

**Comment by wdebusschere** [comment]
Url to pdf extension with a page as pdf. With the above code works smoothly. Last url param of the page sets the filename of the attachement :)

**Comment by michael-e** [comment]
As explained above, this can be rather inefficient, because the PDF will be built for every recipient.

But ok, I will again think about integrating the above code (and adding documentation). Just not today (which is another Monday… some weeks have many Mondays).

**Comment by wdebusschere** [comment]
Ok super, take your time..

We use email_template_manager mostly with 1 recipient (registering, requesting pdf, information, contactform)
