### ISSUE TITLE
What version of this extension should I use?

### ISSUE THREAD

**Issue by ThinkWired** [michael-e/email_template_manager#91]
If I'm running symphony 2.6.9 what release of email_template_manager should I be using?

**Comment by ThinkWired** [comment]
I've uploaded 7.3.2 but, things seem out of sorts. I can no longer see my template and when I try to fill out the email settings, I get the following error.

"Could not save: Template message is set to read-only mode."

**Comment by ThinkWired** [comment]
If I create a new email template and try to delete it, I get the following error.

"Could not delete: Directory ../../workspace/email-templates/quote-request could not be removed. Please check permissions."

If I set every file and folder from workspace down to 777, I still continue to get the same error.

**Comment by michael-e** [comment]
You should use 7.3.2. It works great for me.

Have you double-checked that the `workspace` is writable by the webserver? Thias is needed in order to create the directory and the files.

**Comment by michael-e** [comment]
Oh, regarding deletion, there is an open issue: https://github.com/michael-e/email_template_manager/issues/78

**Comment by ThinkWired** [comment]
Yes, the workspace folder is writeable.

Does the fact that I upgraded from a previous version of this extension and symphony help you any? I wasn't specific in my original post. I had a template in place. That template is no longer editable (the button to edit and the preview button are gone) AND the existing form that was in place saves to the database BUT, the email is never sent. Everything worked fine prior to upgrading.

**Comment by ThinkWired** [comment]
What exactly would trigger the error ...

> "Could not save: Template message is set to read-only mode."

**Comment by michael-e** [comment]
Looking at the [code in question](https://github.com/michael-e/email_template_manager/blob/6e5df593fca4fedada2b167078ec23378281eeff/lib/class.emailtemplatemanager.php#L99-L123), it can only happen if `$editable` is not set to `true` in the email template's PHP file. It might be that, with very old versions of this extension, this variable has not been written to the template.

Please compare [the template file](https://github.com/michael-e/email_template_manager/blob/6e5df593fca4fedada2b167078ec23378281eeff/content/templates/class.tpl) which is used for creating new email templates with your template. Look for `$editable`.

**Comment by ThinkWired** [comment]
Interestingly enough, editable was set to true but, the class.templateName.php in the template folder itself was not exactly the same. I wound up copying the file from a newly created template over to the old template folder and it worked. Not sure why it wasn't updated properly to begin with. Thank you for your help.

**Comment by michael-e** [comment]
You're welcome! Glad that it works now. Regarding the "delete issue", you can always delete templates manually. (But if you use the Email Newsletter **Manager** extension as well, double-check that you have removed the template in question from all newsletter fields).

If everything is solved, please close this issue.
