### ISSUE TITLE
Undefined array key "layouts"

### ISSUE THREAD

**Issue by tiloschroeder** [michael-e/email_template_manager#99]
I run into this issue when creating or updating a newsletter template with both layouts (html and plain).

If you replace in the ```content/content.template.php``` on ```line 40``` and ```88``` 
```php
unset($fields['layouts']);
```
with 
```php
$fields['layouts'] = array('html' => 'template.html.xsl', 'plain' => 'template.plain.xsl');
```
then it works fine.

Testet on localhost with
- PHP 8.1.16
- Symphony 2.7.10 with the [ugrade instructions from Phil](https://github.com/pixelninja/symphonycms-php8)
- Members and ENM extensions also from @pixelninja

**Comment by michael-e** [comment]
Yes, your solution is fine (and even easier to understand), so I will implement it.

But please note that currently I do not intend to make Email Template Manager "officially" compatible with PHP 8. (Simply because there is no properly maintained Symphony version for PHP 8.)
